# Generated by Django 3.0.8 on 2020-07-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cropType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='cropPrice',
            new_name='cropPricePerUnit',
        ),
        migrations.AddField(
            model_name='crop',
            name='cropType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.cropType'),
        ),
    ]
