# Generated by Django 3.0.8 on 2020-07-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200728_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaler',
            name='address',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='city',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='idType',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='state',
        ),
        migrations.RemoveField(
            model_name='wholesaler',
            name='zipcode',
        ),
    ]
