# Generated by Django 3.0.8 on 2020-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200729_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='idType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='idType',
        ),
    ]
