# Generated by Django 3.0.8 on 2020-08-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200801_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop',
            new_name='name',
        ),
    ]
